<?php
session_start();
include_once '../assets/php-header.php';

?>

<div class="content-inner">

  <h2 title="Privacy Policy">Privacy Policy</h2>
  <p>Your privacy is important. To better protect your privacy, this notice explains the way your information is collected and used.</p>

  <h3>Information we receive and how it is used</h3>
  <p>We receive a number of different types of information about you, including:</p>

  <h4><strong>Your information</strong></h4>
  <ul>
    <li>Your information is the information that's required when you sign up for the site, as well as the information you choose to share.</li>
  </ul>

  <h4>Registration information</h4>
  <ul>
    <li>When you sign up for nesmonsters.com, you are required to provide your full name, email address, a username, a password, and must agree to the Terms of Service and this Privacy Statement.</li>
  </ul>

  <h4>Information you choose to share</h4>
  <ul>
    <li>Your information also includes the information you choose to share on nesmonsters.com, such as when you answer any questions, email messages to other registered users on nesmonsters.com, or contact nesmonsters.com.</li>
  </ul>

  <h3>How we use the information we receive</h3>
  <p>We use the different types of information we receive in many ways, including:</p>

  <h4>Your information</h4>
  <ul>
    <li>Your username can be can be viewed by any user of the nesmonsters.com web site while viewing any answers to questions that you have saved.</li>
    <li>Any answers to any questions that you save can be viewed by any user of the nesmonsters.com web site.</li>
  </ul>

  <h4>Registration Information</h4>
  <ul>
    <li>Your full name, email address, and password are not shown to other users of the website.</li>
  </ul>

  <h4>Information you choose to share</h4>
  <ul>
    <li>Only users who are registered and signed in with nesmonsters.com are able to send another user an email message.</li>
    <li>The email address and username of the sender of the email message is revealed to the recipient of the email message.</li>
    <li>The email address of the recipient is only revealed if the recipient chooses to reply to the email message directly.</li>
    <li>Email messages sent between users, including the originating email message generated by nesmonsters.com, are not monitored, regulated, or used by nesmonsters.com.</li>
  </ul>

  <h3>Disclosure to Third Parties</h3>
  <p>At times nesmonsters.com may make certain personal information available to strategic partners that work with nesmonsters.com to provide and improve our services, content, and advertising.</p>

  <p>
    <strong>Others</strong><br />
    It may be necessary &#8212; by law, legal process, litigation, and/or requests from public and governmental authorities within or outside your country of residence &#8212; for nesmonsters.com to disclose your personal information. We may also disclose information about you if we determine that for purposes of national security, law enforcement, or other issues of public importance, disclosure is necessary or appropriate.
  </p>
  <p>We may also disclose information about you if we determine that disclosure is reasonably necessary to enforce our terms and conditions or protect our operations or users. Additionally, in the event of a reorganization, merger, or sale we may transfer any and all personal information we collect to the relevant third party.</p>

  <p><em><strong>The information contained in this web site is subject to change without notice.</strong></em></p>
  <p>Last updated on April 15, 2012</p>

</div>

<?php

include_once '../assets/php-footer.php';

?>
